### ISSUE TITLE
No such file or directory: '/mnt/multimodal/data/text/data-bin/tnlg/dict.txt

### ISSUE THREAD

**Issue by L16H7** [Victorwz/LongMem#11]
I got the following error trace when I run the evaluation with this <br>`python eval_scripts/eval_longmem_icl.py --path ../LongMem_public_checkpoints/longmem_gpt2_medium/checkpoint_last.pt --pretrained-model-path ../LongMem_public_checkpoints/gpt2_medium/checkpoint_last.pt`

`
Traceback (most recent call last):
  File "eval_scripts/eval_longmem_icl.py", line 171, in <module>
    main(args)
  File "eval_scripts/eval_longmem_icl.py", line 102, in main
    model, _ = load_model_ensemble([args.path], arg_overrides=override_args, task=None)
  File "/home/ubuntu/longmem/LongMem/fairseq/fairseq/checkpoint_utils.py", line 368, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(
  File "/home/ubuntu/longmem/LongMem/fairseq/fairseq/checkpoint_utils.py", line 443, in load_model_ensemble_and_task
    task = tasks.setup_task(cfg.task)
  File "/home/ubuntu/longmem/LongMem/fairseq/fairseq/tasks/__init__.py", line 49, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/home/ubuntu/longmem/LongMem/fairseq/fairseq/tasks/language_modeling.py", line 183, in setup_task
    dictionary, output_dictionary = cls.setup_dictionary(args, **kwargs)
  File "/home/ubuntu/longmem/LongMem/fairseq/fairseq/tasks/language_modeling.py", line 167, in setup_dictionary
    dictionary = Dictionary.load(os.path.join(paths[0], "dict.txt"))
  File "/home/ubuntu/longmem/LongMem/fairseq/fairseq/data/dictionary.py", line 226, in load
    d.add_from_file(f)
  File "/home/ubuntu/longmem/LongMem/fairseq/fairseq/data/dictionary.py", line 239, in add_from_file
    raise fnfe
  File "/home/ubuntu/longmem/LongMem/fairseq/fairseq/data/dictionary.py", line 236, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/multimodal/data/text/data-bin/tnlg/dict.txt'
`

Thank you for adding more scripts.

**Comment by Victorwz** [comment]
This bug is fixed. Sincerely apologize for the bug I made.

**Comment by L16H7** [comment]
Thank you so much. I see it's fixed.
