### ISSUE TITLE
RuntimeError: Expected hasRecord("version") to be true, but got false.

### ISSUE THREAD

**Issue by JornyWan** [Victorwz/LongMem#15]
sorry, i try to evaluate your trained model directly, but received this error:

Traceback (most recent call last):
  File "eval_scripts/eval_longmem_icl.py", line 168, in <module>
    main(args)
  File "eval_scripts/eval_longmem_icl.py", line 99, in main
    model, _ = load_model_ensemble([args.path], arg_overrides=override_args, task=None)
  File "/data/cwan38/trial/LongMem/fairseq/fairseq/checkpoint_utils.py", line 367, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(
  File "/data/cwan38/trial/LongMem/fairseq/fairseq/checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/data/cwan38/trial/LongMem/fairseq/fairseq/checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "/data/cwan38/anaconda3/envs/longmem/lib/python3.8/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/data/cwan38/anaconda3/envs/longmem/lib/python3.8/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: Expected hasRecord("version") to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

**Comment by JornyWan** [comment]
anyone can fix this?
